GMS/GMS/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GMS.Models;

namespace GMS.Controllers
{
    public class LayoutController : Controller
    {
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["con"].ConnectionString);

        // GET: Layout
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MentorLeftMenu()
        {
            if (Session["UserEmail"] != null)
            {
                if (Session["UserType"].Equals("Mentor"))
                {
                    SqlCommand cmd = new SqlCommand("SelectMentorProfile", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@email", Session["UserEmail"].ToString());
                    con.Open();

                    SqlDataReader dr = cmd.ExecuteReader();
                    dr.Read();
                    if (dr.HasRows)
                    {

                        MentorTopItem mp = new MentorTopItem
                        {

                            Name = dr["Name"].ToString(),
                            Image = dr["Image"].ToString(),
                            Email = dr["Email"].ToString()


                        };
                        ViewData["MyMP"] = mp;

                        con.Close();
                        return PartialView();
                    }
                    else
                    {
                        return RedirectToAction("login", "user");
                    }
                }
                else if (Session["UserType"].Equals("User"))
                {
                    SqlCommand cmd = new SqlCommand("SelectUserProfile", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@email", Session["UserEmail"].ToString());
                    con.Open();

                    SqlDataReader dr = cmd.ExecuteReader();
                    dr.Read();
                    if (dr.HasRows)
                    {

                        MentorTopItem mp = new MentorTopItem
                        {

                            Name = dr["Name"].ToString(),
                            Image = dr["Image"].ToString(),
                            Email = dr["Email"].ToString()

                        };
                        ViewData["MyMP"] = mp;

                        con.Close();
                        return PartialView();
                    }
                    else
                    {
                        return RedirectToAction("login", "user");
                    }
                }
                else
                {
                    return RedirectToAction("login", "user");
                }

            }
            else
            {
                return PartialView() ;
            }
        }
        public ActionResult StartupRecommendation()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.StartupRecommendation = GetStartups();
            mymodel.DemoRecommendation = GetDemos();

            return PartialView(mymodel);
        }
        public List<StartupRecommendation> GetStartups()
        {
            List<StartupRecommendation> list = new List<StartupRecommendation>();

            DataTable dt = new DataTable();
            SqlDataAdapter da = new SqlDataAdapter();
            da.SelectCommand = new SqlCommand("SelectAllUser", con);

            da.Fill(dt);

            foreach (DataRow row in dt.Rows)
            {
                var startupRecommendation = new StartupRecommendation();
                startupRecommendation.Id = Convert.ToInt32(row["Id"].ToString());
                startupRecommendation.Name = row["Name"].ToString();
                startupRecommendation.Image = row["Image"].ToString();
                startupRecommendation.Industry = row["Industry"].ToString();

                list.Add(startupRecommendation);

            }
            return list;
        }
        public List<DemoRecommendation> GetDemos()
        {
            List<DemoRecommendation> DemoRecommendation = new List<DemoRecommendation>();
            DemoRecommendation.Add(new DemoRecommendation { Id = 1, Date = "21-Nov-2019", Name = "Amit Gupta", Time = "10:00 am" ,Image="knkn", Address= "St Johns Auditorium" });
            DemoRecommendation.Add(new DemoRecommendation { Id = 2, Date = "20-Nov-2019", Name = "Chetan Gujjar", Time = "10:00 am", Image = "knkn", Address = "St Johns Auditorium" });
            DemoRecommendation.Add(new DemoRecommendation { Id = 3, Date = "19-Nov-2019", Name = "Bhavin Patel", Time = "10:00 am", Image = "knkn", Address = "St Johns Auditorium" });
            return DemoRecommendation;
        }
        public ActionResult Footer()
        {
            return PartialView();
        }
        public ActionResult TopMenu()
        {
            if (Session["UserEmail"] != null)
            {
                if (Session["UserType"].ToString()=="Mentor")
                {
                    SqlCommand cmd = new SqlCommand("SelectMentorTop", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@email", Session["UserEmail"].ToString());
                    con.Open();

                    SqlDataReader dr = cmd.ExecuteReader();
                    dr.Read();
                    if (dr.HasRows)
                    {

                        MentorTopItem mp = new MentorTopItem
                        {

                            Name = dr["Name"].ToString(),
                            Image = dr["Image"].ToString(),


                        };
                        ViewData["MyMP"] = mp;

                        con.Close();
                        return PartialView();
                    }
                    else
                    {
                        return RedirectToAction("login", "user");
                    }
                }
                else if (Session["UserType"].ToString()=="User")
                {
                    SqlCommand cmd = new SqlCommand("SelectUserTop", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@email", Session["UserEmail"].ToString());
                    con.Open();

                    SqlDataReader dr = cmd.ExecuteReader();
                    dr.Read();
                    if (dr.HasRows)
                    {

                        MentorTopItem mp = new MentorTopItem
                        {

                            Name = dr["Name"].ToString(),
                            Image = dr["Image"].ToString(),


                        };
                        ViewData["MyMP"] = mp;

                        con.Close();
                        return PartialView();
                    }
                    else
                    {
                        return RedirectToAction("login", "user");
                    }
                }
                else
                {
                    return RedirectToAction("login", "user");
                }
               
            }
            else
            {
                return PartialView();
            }
        }
        public ActionResult StartupLeftMenu()
        {
            if (Session["UserEmail"] != null)
            {
                if (Session["UserType"].Equals("Mentor"))
                {
                    SqlCommand cmd = new SqlCommand("SelectMentorProfile", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@email", Session["UserEmail"].ToString());
                    con.Open();

                    SqlDataReader dr = cmd.ExecuteReader();
                    dr.Read();
                    if (dr.HasRows)
                    {

                        MentorTopItem mp = new MentorTopItem
                        {

                            Name = dr["Name"].ToString(),
                            Image = dr["Image"].ToString(),
                            Email = dr["Email"].ToString()


                        };
                        ViewData["MyMP"] = mp;

                        con.Close();
                        return PartialView();
                    }
                    else
                    {
                        return RedirectToAction("login", "user");
                    }
                }
                else if (Session["UserType"].Equals("User"))
                {
                    SqlCommand cmd = new SqlCommand("SelectUsersProfile", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@email", Session["UserEmail"].ToString());
                    con.Open();

                    SqlDataReader dr = cmd.ExecuteReader();
                    dr.Read();
                    if (dr.HasRows)
                    {

                        MentorTopItem mp = new MentorTopItem
                        {

                            Name = dr["Name"].ToString(),
                            Image = dr["Image"].ToString(),
                            Email = dr["Email"].ToString()

                        };
                        ViewData["MyMP"] = mp;

                        con.Close();
                        return PartialView();
                    }
                    else
                    {
                        return RedirectToAction("login", "user");
                    }
                }
                else
                {
                    return RedirectToAction("login", "user");
                }

            }
            else
            {

GMS/GMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-US" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="description" content="StartupLink">
    <meta name="keywords" content="StartupLink">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
    <title>India's no. startup mentorship and virtual incubition platform- GMS</title>
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/vnd.microsoft.icon" />
    <link href="~/assets/formValidation/formValidation.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/owl.carousel.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-select.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-datetimepicker.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-clockpicker.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/style.css" type="text/css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script type="text/javascript" src="~/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/formValidation/formValidation.min.js"></script>
    <script type="text/javascript" src="~/assets/formValidation/js/framework/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/custom-file-input.js"></script>
    <script type="text/javascript" src="~/assets/js/moment.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-clockpicker.min.js"></script>
    <script type="text/javascript" src="~/assets/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-select.min.js"></script>
    <script type="text/javascript" src="~/assets/js/readmore.min.js"></script>
    <script type="text/javascript" src="~/assets/js/custom.js"></script>
    <script type="text/javascript" src="~/assets/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/js/jquery.validate.min.js"></script>
    <script>
            var base_url = '/';
    </script>
    <script type="text/javascript" src="~/assets/js/jquery.raty.js"></script>




</head>




<body class="">
  

  @Html.Action("TopMenu","Layout")

    <style>
        /*custom css*/

        section.section.gradient {
            padding: 0;
        }

            section.section.gradient .container {
                padding: 30px 0;
            }

        .hp-banner-caption h2 {
            margin: 0;
        }

        section.section.about-mentor.bg-grey {
            padding: 30px 0;
        }

        .indicator {
            display: none;
        }

        .hp-banner-caption .row .col-md-6:nth-child(1) {
            border-right: 1px solid #fff;
        }

        .hp-banner-caption .row .col-md-6 h2.mentor-heading {
            margin-left: 20%;
        }

        .hp-banner-caption .row .col-md-6 p.mentor-content {
            margin-left: 100px;
        }

        .hp-banner-caption .btn-lg.mentor-signup {
            margin-left: 20%;
        }

        .hp-banner-caption .row .col-md-6 h2.startup-heading {
            margin-right: 20%;
        }

        .hp-banner-caption .row .col-md-6 p.startup-content {
            margin-right: 100px;
        }

        .hp-banner-caption .btn-lg.startup-signup {
            margin-right: 20%;
        }

        section#home-slider {
            height: 530px;
        }

        /*mobile responsive media*/
        @@media only screen and (min-width:320px) and (max-width:330px) {
            .hp-banner-caption .row .col-md-6 h2.mentor-heading {
                margin-top: 30px;
            }
        }

        @@media only screen and (min-width:320px) and (max-width: 480px) {
            section#home-slider {
                height: auto;
            }

            .hp-banner-caption .row .col-md-6:nth-child(1) {
                border-right: 0;
                margin-bottom: 20px;
            }

            .hp-banner-caption .row .col-md-6 h2.mentor-heading {
                margin-left: 0;
            }

            .hp-banner-caption .row .col-md-6 p.mentor-content {
                margin-left: 0;
            }

            .hp-banner-caption .btn-lg.mentor-signup {
                margin-left: 0;
            }

            .hp-banner-caption .row .col-md-6 h2.startup-heading {
                margin-right: 0;
            }

            .hp-banner-caption .row .col-md-6 p.startup-content {
                margin-right: 0;
            }

            .hp-banner-caption .btn-lg.startup-signup {
                margin-right: 0;
            }
        }

        @@media only screen and (min-width:481px) and (max-width: 767px) {
            section#home-slider {
                height: auto;
            }

            .hp-banner-caption .row .col-md-6:nth-child(1) {
                border-right: 0;
                margin-bottom: 20px;
            }

            .hp-banner-caption .row .col-md-6 h2.mentor-heading {
                margin-left: 0;
            }

            .hp-banner-caption .row .col-md-6 p.mentor-content {
                margin-left: 0;
            }

            .hp-banner-caption .btn-lg.mentor-signup {
                margin-left: 0;
            }

            .hp-banner-caption .row .col-md-6 h2.startup-heading {
                margin-right: 0;
            }

            .hp-banner-caption .row .col-md-6 p.startup-content {
                margin-right: 0;
            }

            .hp-banner-caption .btn-lg.startup-signup {
                margin-right: 0;
            }
        }

        @@media only screen and (min-width:768px) and (max-width: 991px) {
            section#home-slider {
                height: auto;
            }

            .hp-banner-caption .row .col-md-6:nth-child(1) {
                border-right: 0;
                margin-bottom: 20px;
            }

            .hp-banner-caption .row .col-md-6 h2.mentor-heading {
                margin-left: 0;
            }

            .hp-banner-caption .row .col-md-6 p.mentor-content {
                margin-left: 0;
            }

            .hp-banner-caption .btn-lg.mentor-signup {
                margin-left: 0;
            }

            .hp-banner-caption .row .col-md-6 h2.startup-heading {
                margin-right: 0;
            }

            .hp-banner-caption .row .col-md-6 p.startup-content {
                margin-right: 0;
            }

            .hp-banner-caption .btn-lg.startup-signup {
                margin-right: 0;
            }
        }

        @@media only screen and (min-width:992px) and (max-width: 1199px) {
            section#home-slider {
                height: auto;
            }
        }
    </style>

    <style type="text/css">
        html, body {
            height: 100%;
        }
    </style>

   
        

        @RenderBody()

        <style>

            /* Centered text */
            .centered {
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                font-weight: 700;
                color: #443f3f;
                font-size: 32px;
                margin: 0;
                text-transform: uppercase;
                letter-spacing: -2px;
            }

            .asdasdasdas {
                cursor: pointer;
                opacity: 0.9;
                margin-bottom: 20px;
            }

                .asdasdasdas:hover {
                    cursor: pointer;
                    opacity: 0.5;
                }

            .chips-view span {
                font-size: 10px;
                font-weight: 500;
                padding: 4px !important;
                margin: 0 2px 3px 0 !important;
                background: #f4f3f3;
            }

            .mentors .mid-body {
                min-height: 65px !important;
            }

            .mentors {
                height: 550px;
            }
        </style>
        <script type="text/javascript" src="~/assets/js/common.js"></script>
        <!--[Footer]-->
       @Html.Action("Footer","Layout")
        <!--[/Footer]-->


       
</body>
</html>

GMS/GMS/Views/Shared/_LayoutMentor.cshtml
<!DOCTYPE html>
<!--[if IE 8]><html class="ie ie8" lang="en-US"><![endif]-->
<!--[if !(IE 8)]><!-->
<html lang="en-US" class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="description" content="StartupLink">
    <meta name="keywords" content="StartupLink">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
    <title>GMS</title>
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/vnd.microsoft.icon" />
    <link href="~/assets/formValidation/formValidation.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/owl.carousel.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-select.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-datetimepicker.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-clockpicker.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/style.css" type="text/css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script type="text/javascript" src="~/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/formValidation/formValidation.min.js"></script>
    <script type="text/javascript" src="~/assets/formValidation/js/framework/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/custom-file-input.js"></script>
    <script type="text/javascript" src="~/assets/js/moment.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-clockpicker.min.js"></script>
    <script type="text/javascript" src="~/assets/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-select.min.js"></script>
    <script type="text/javascript" src="~/assets/js/readmore.min.js"></script>
    <script type="text/javascript" src="~/assets/js/custom.js"></script>
    <script type="text/javascript" src="~/assets/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/js/jquery.validate.min.js"></script>
    <script>
        var base_url = '/';
    </script>
    <script type="text/javascript" src="~/assets/js/jquery.raty.js"></script>


</head>


<body class="">
    <!--[Header]-->

    @Html.Action("TopMenu","Layout")
    <!--[Banner]-->
    <div class="user-cover-img" style="background-image:url(/assets/images/cover.jpg)"></div>
    <!--[/Banner]-->
    <!--[Dashboard]-->
    <section class="dashboard data-table">
        @Html.Action("MentorLeftMenu", "Layout")

        @RenderBody()

        @Html.Action("StartupRecommendation", "Layout")

    </section>
    <!--[/Dashboard]-->



    <script type="text/javascript" src="~/assets/js/common.js"></script>
    <!--[Footer]-->
    @Html.Action("Footer", "Layout")
    <!--[/Footer]-->







</body>
</html>

GMS/GMS/Views/Shared/_LayoutStartup.cshtml
<!DOCTYPE html>
<!--[if IE 8]><html class="ie ie8" lang="en-US"><![endif]-->
<!--[if !(IE 8)]><!-->
<html lang="en-US" class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="description" content="StartupLink">
    <meta name="keywords" content="StartupLink">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
    <title>GMS</title>
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/vnd.microsoft.icon" />
    <link href="~/assets/formValidation/formValidation.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/owl.carousel.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-select.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-datetimepicker.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-clockpicker.min.css" type="text/css" rel="stylesheet">
    <link href="~/assets/css/style.css" type="text/css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script type="text/javascript" src="~/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/formValidation/formValidation.min.js"></script>
    <script type="text/javascript" src="~/assets/formValidation/js/framework/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/custom-file-input.js"></script>
    <script type="text/javascript" src="~/assets/js/moment.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-clockpicker.min.js"></script>
    <script type="text/javascript" src="~/assets/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-select.min.js"></script>
    <script type="text/javascript" src="~/assets/js/readmore.min.js"></script>
    <script type="text/javascript" src="~/assets/js/custom.js"></script>
    <script type="text/javascript" src="~/assets/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/js/jquery.validate.min.js"></script>
    <script>
        var base_url = '/';
    </script>
    <script type="text/javascript" src="~/assets/js/jquery.raty.js"></script>


</head>


<body class="">
    <!--[Header]-->

    @Html.Action("TopMenu","Layout")
    <!--[Banner]-->
    <div class="user-cover-img" style="background-image:url(/assets/images/cover.jpg)"></div>
    <!--[/Banner]-->
    <!--[Dashboard]-->
    <section class="dashboard data-table">
        @Html.Action("StartupLeftMenu", "Layout")

        @RenderBody()

        @Html.Action("MentorRecommendation", "Layout")

    </section>
    <!--[/Dashboard]-->



    <script type="text/javascript" src="~/assets/js/common.js"></script>
    <!--[Footer]-->
    @Html.Action("Footer", "Layout")
    <!--[/Footer]-->







</body>
</html>